theme: jekyll-theme-cayman
title: Os Desafios e Oportunidades da Gerontecnologia para o Brasil
description: Apresentação para o curso "Gerontecnologia - Princípios e práticas para apoiar a sociedade em envelhecimento", da Sociedade Brasileira de Gerontecnologia.
show_downloads: true